name: Reshaper Code Analysis

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
      
      - name: Add xunit Package
        run: dotnet add AlertToCareUnitTest/AlertToCareUnitTest.csproj package xunit --version 2.4.0
      
      - name: Add Entity Framework Package
        run: dotnet add AlertToCareApi/AlertToCareApi.csproj package Microsoft.EntityFrameworkCore --version 3.1.9
        
      - name: Run resharper inspection
        run: jb inspectcode AlertToCareApi.sln /output=insreport.xml

      - name: Run resharper duplicate code check
        run: jb dupfinder AlertToCareApi.sln /output=dupreport.xml

      - name: Check Reports
        run: powershell ./resharper.ps1
